services:


  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "${MAILHOG_SMTP_PORT:-2525}:1025"
      - "${MAILHOG_HTTP_PORT:-8025}:8025"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrate
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://app:app@db:5432/app}
    depends_on:
      - db
    command: ["npm", "run", "db:push"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000}
      DATABASE_URL: ${DATABASE_URL:-postgresql://app:app@db:5432/app}
      SMTP_HOST: ${SMTP_HOST:-mailhog}
      SMTP_PORT: ${SMTP_PORT:-1025}
      SMTP_SECURE: ${SMTP_SECURE:-false}
      MAIL_FROM: ${MAIL_FROM:-"Dev <dev@example.test>"}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-dev_only_change_me_but_at_least_32_chars_long}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailhog

volumes:
  pgdata:
