import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import {NextIntlClientProvider} from 'next-intl';
import { TRPCReactProvider } from "@/trpc/client";
import { ThemeProvider } from "@/components/ui/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'cs'}];
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {

  const { locale } = await params
  const messages = (await import(`@/messages/${locale}.json`)).default;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <TRPCReactProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                <div className="relative min-h-screen overflow-hidden bg-background">
                {/* Gradient overlay */}
                <div className="fixed inset-0 bg-gradient-to-br from-accent/5 via-accent/10 to-accent/5" />

                {/* Blurred ornamental shapes */}
                <div className="fixed inset-0 overflow-hidden pointer-events-none">
                  <div className="absolute top-0 right-0 w-96 h-96 bg-accent/20 rounded-full blur-3xl" />
                  <div className="absolute bottom-0 left-0 w-96 h-96 bg-accent/15 rounded-full blur-3xl" />
                  <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[32rem] h-[32rem] bg-accent/10 rounded-full blur-3xl" />
                </div>

                {/* Content */}
                <div className="relative z-10">
                  <NextIntlClientProvider locale={locale} messages={messages}>
                    {children}
                    <Toaster />
                  </NextIntlClientProvider>
                </div>
              </div>
            </ThemeProvider>
          </TRPCReactProvider>
      </body>
    </html>
  );
}
